import React, { useState } from 'react';
import { Copy, Check, Download, Maximize2, Share2, Code } from 'lucide-react';

interface ArtifactToolbarProps {
  code: string;
  title: string;
  type: string;
  version: number;
  onToggleCodeView?: () => void;
  showCodeView?: boolean;
}

export default function ArtifactToolbar({
  code,
  title,
  type,
  version,
  onToggleCodeView,
  showCodeView = false,
}: ArtifactToolbarProps) {
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([code], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-v${version}.html`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    // Generate simple share text
    const text = `Check out this interactive artifact: ${title} (version ${version}) generated by 3RDMIND!`;
    navigator.clipboard.writeText(text);
    setShared(true);
    setTimeout(() => setShared(false), 2000);
  };

  const handleFullscreen = () => {
    // Try to request fullscreen on parent element or iframe
    const sandboxIframe = document.querySelector('iframe[title="Live Preview Sandbox"]') || document.querySelector('iframe');
    if (sandboxIframe) {
      if (sandboxIframe.requestFullscreen) {
        sandboxIframe.requestFullscreen();
      }
    }
  };

  return (
    <div className="bg-[#FAF9F6] border-b border-[#E5E0DA] px-4 py-2 flex items-center justify-between shrink-0 font-dmsans">
      <div className="flex items-center gap-2">
        <span className="text-[10px] font-bold text-white bg-neutral-900 uppercase px-2 py-0.5 rounded-sm">
          {type}
        </span>
        <span className="text-xs font-bold text-[#191919] truncate max-w-[150px] font-lora">
          v{version} • {title}
        </span>
      </div>

      <div className="flex items-center gap-1.5">
        {/* Toggle Code / Preview */}
        {onToggleCodeView && (
          <button
            onClick={onToggleCodeView}
            className={`p-1.5 rounded-lg border transition-all cursor-pointer ${
              showCodeView
                ? 'bg-neutral-900 text-white border-neutral-900'
                : 'bg-white text-[#5E5B56] border-[#E5E0DA] hover:text-[#191919] hover:bg-[#F2EFEA]'
            }`}
            title={showCodeView ? 'Show Preview' : 'Show Source Code'}
          >
            <Code className="w-3.5 h-3.5" />
          </button>
        )}

        {/* Copy Code */}
        <button
          onClick={handleCopy}
          className="p-1.5 bg-white border border-[#E5E0DA] hover:border-[#191919] rounded-lg text-[#5E5B56] hover:text-[#191919] hover:bg-[#F2EFEA] transition-all cursor-pointer"
          title="Copy Code"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
        </button>

        {/* Download File */}
        <button
          onClick={handleDownload}
          className="p-1.5 bg-white border border-[#E5E0DA] hover:border-[#191919] rounded-lg text-[#5E5B56] hover:text-[#191919] hover:bg-[#F2EFEA] transition-all cursor-pointer"
          title="Download HTML"
        >
          <Download className="w-3.5 h-3.5" />
        </button>

        {/* Fullscreen */}
        <button
          onClick={handleFullscreen}
          className="p-1.5 bg-white border border-[#E5E0DA] hover:border-[#191919] rounded-lg text-[#5E5B56] hover:text-[#191919] hover:bg-[#F2EFEA] transition-all cursor-pointer"
          title="Fullscreen Sandbox"
        >
          <Maximize2 className="w-3.5 h-3.5" />
        </button>

        {/* Share */}
        <button
          onClick={handleShare}
          className="p-1.5 bg-white border border-[#E5E0DA] hover:border-[#191919] rounded-lg text-[#5E5B56] hover:text-[#191919] hover:bg-[#F2EFEA] transition-all cursor-pointer"
          title="Share Link"
        >
          {shared ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Share2 className="w-3.5 h-3.5" />}
        </button>
      </div>
    </div>
  );
}
