import { ConnectorConfig } from '../types';

export const ALL_CONNECTORS: ConnectorConfig[] = [
  // --- OAUTH CONNECTORS (15) ---
  {
    slug: 'google-drive',
    name: 'Google Drive',
    category: 'storage',
    description: 'Browse folders, download files, and write documents directly in Google Drive.',
    authType: 'oauth',
    icon: 'ti-brand-google-drive',
    docsUrl: 'https://developers.google.com/drive',
    scopes: [
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/drive.file'
    ],
    serverUrl: 'https://gdrive.mcp.goog/mcp',
    tools: ['drive_search', 'drive_read', 'drive_create', 'drive_upload']
  },
  {
    slug: 'gmail',
    name: 'Gmail',
    category: 'communication',
    description: 'Search user mailboxes, read emails, draft replies, and send messages.',
    authType: 'oauth',
    icon: 'ti-brand-gmail',
    docsUrl: 'https://developers.google.com/gmail/api',
    scopes: [
      'https://www.googleapis.com/auth/gmail.send',
      'https://www.googleapis.com/auth/gmail.readonly',
      'https://www.googleapis.com/auth/gmail.modify'
    ],
    serverUrl: 'https://gmail.mcp.goog/mcp',
    tools: ['gmail_send', 'gmail_read', 'gmail_search', 'gmail_draft']
  },
  {
    slug: 'google-calendar',
    name: 'Google Calendar',
    category: 'productivity',
    description: 'List calendar events, schedule appointments, and coordinate availability.',
    authType: 'oauth',
    icon: 'ti-calendar',
    docsUrl: 'https://developers.google.com/calendar',
    scopes: [
      'https://www.googleapis.com/auth/calendar',
      'https://www.googleapis.com/auth/calendar.events'
    ],
    serverUrl: 'https://calendar.mcp.goog/mcp',
    tools: ['calendar_list_events', 'calendar_create_event', 'calendar_update_event']
  },
  {
    slug: 'slack',
    name: 'Slack',
    category: 'communication',
    description: 'Post messages to channels, read active workspace threads, and send alerts.',
    authType: 'oauth',
    icon: 'ti-brand-slack',
    docsUrl: 'https://api.slack.com',
    scopes: ['channels:read', 'chat:write', 'files:read', 'users:read'],
    serverUrl: 'https://mcp.slack.com/sse',
    tools: ['slack_send_message', 'slack_list_channels', 'slack_read_messages', 'slack_upload_file']
  },
  {
    slug: 'github',
    name: 'GitHub',
    category: 'developer',
    description: 'Search repositories, view issues, file pull requests, and commit code.',
    authType: 'oauth',
    icon: 'ti-brand-github',
    docsUrl: 'https://github.com/features/copilot',
    scopes: ['repo', 'read:user', 'read:org'],
    serverUrl: 'https://api.githubcopilot.com/mcp',
    tools: ['github_search_repos', 'github_read_file', 'github_create_issue', 'github_create_pr', 'github_list_issues', 'github_commit']
  },
  {
    slug: 'notion',
    name: 'Notion',
    category: 'productivity',
    description: 'Access pages, databases, and workspaces in Notion to read and write notes.',
    authType: 'oauth',
    icon: 'ti-brand-notion',
    docsUrl: 'https://developers.notion.com',
    scopes: [],
    serverUrl: 'https://mcp.notion.com',
    tools: ['notion_search', 'notion_read_page', 'notion_create_page', 'notion_update_page', 'notion_list_databases', 'notion_query_database']
  },
  {
    slug: 'linear',
    name: 'Linear',
    category: 'productivity',
    description: 'Track issues, cycles, and projects inside Linear, allowing agents to file tickets.',
    authType: 'oauth',
    icon: 'ti-circle-dot',
    docsUrl: 'https://linear.app/docs',
    scopes: ['read', 'write', 'issues:create'],
    serverUrl: 'https://mcp.linear.app/sse',
    tools: ['linear_list_issues', 'linear_create_issue', 'linear_update_issue', 'linear_list_projects']
  },
  {
    slug: 'jira',
    name: 'Jira',
    category: 'productivity',
    description: 'Convene tickets and update task progress inside Atlassian Jira projects.',
    authType: 'oauth',
    icon: 'ti-brand-trello',
    docsUrl: 'https://developer.atlassian.com/cloud/jira/platform',
    scopes: ['read:jira-work', 'write:jira-work'],
    serverUrl: 'https://mcp.atlassian.com/jira',
    tools: ['jira_list_issues', 'jira_create_issue', 'jira_update_issue', 'jira_search']
  },
  {
    slug: 'outlook',
    name: 'Outlook',
    category: 'communication',
    description: 'Read and send emails, manage calendar meetings, and configure schedules.',
    authType: 'oauth',
    icon: 'ti-mail',
    docsUrl: 'https://learn.microsoft.com/en-us/graph/outlook-mail-concept-overview',
    scopes: ['Mail.Read', 'Mail.Send', 'Calendars.ReadWrite'],
    serverUrl: 'https://outlook.mcp.microsoft.com/mcp',
    tools: ['outlook_send', 'outlook_read', 'outlook_search', 'outlook_calendar']
  },
  {
    slug: 'onedrive',
    name: 'OneDrive',
    category: 'storage',
    description: 'Manage personal cloud documents, list folders, and sync team assets.',
    authType: 'oauth',
    icon: 'ti-cloud',
    docsUrl: 'https://learn.microsoft.com/en-us/graph/onedrive-concept-overview',
    scopes: ['Files.ReadWrite', 'Sites.Read.All'],
    serverUrl: 'https://onedrive.mcp.microsoft.com/mcp',
    tools: ['onedrive_search', 'onedrive_read', 'onedrive_upload', 'onedrive_create_folder']
  },
  {
    slug: 'hubspot',
    name: 'HubSpot',
    category: 'crm',
    description: 'Query contacts, update sales deals, and synchronize client interactions.',
    authType: 'oauth',
    icon: 'ti-circles-relation',
    docsUrl: 'https://developers.hubspot.com',
    scopes: ['crm.objects.contacts.read', 'crm.objects.contacts.write', 'crm.objects.deals.read'],
    serverUrl: 'https://mcp.hubspot.com/mcp',
    tools: ['hubspot_search_contacts', 'hubspot_create_contact', 'hubspot_create_deal', 'hubspot_list_deals']
  },
  {
    slug: 'salesforce',
    name: 'Salesforce',
    category: 'crm',
    description: 'Query CRM objects, update sales records, and run custom SOQL queries.',
    authType: 'oauth',
    icon: 'ti-cloud-storm',
    docsUrl: 'https://developer.salesforce.com',
    scopes: ['api', 'refresh_token'],
    serverUrl: 'https://mcp.salesforce.com/mcp',
    tools: ['salesforce_query', 'salesforce_create', 'salesforce_update', 'salesforce_search']
  },
  {
    slug: 'dropbox',
    name: 'Dropbox',
    category: 'storage',
    description: 'Share links, list file hierarchies, and write content to user folders.',
    authType: 'oauth',
    icon: 'ti-brand-dropbox',
    docsUrl: 'https://www.dropbox.com/developers',
    scopes: ['files.content.read', 'files.content.write'],
    serverUrl: 'https://mcp.dropbox.com/mcp',
    tools: ['dropbox_search', 'dropbox_read', 'dropbox_upload', 'dropbox_share']
  },
  {
    slug: 'discord',
    name: 'Discord',
    category: 'communication',
    description: 'Post webhook updates, read channel threads, and notify servers.',
    authType: 'oauth',
    icon: 'ti-brand-discord',
    docsUrl: 'https://discord.com/developers/docs/intro',
    scopes: ['bot', 'messages.read'],
    serverUrl: 'https://mcp.discord.com/mcp',
    tools: ['discord_send_message', 'discord_read_channel', 'discord_list_channels']
  },
  {
    slug: 'asana',
    name: 'Asana',
    category: 'productivity',
    description: 'Coordinate workspaces, delegate task lists, and track project status.',
    authType: 'oauth',
    icon: 'ti-layout-kanban',
    docsUrl: 'https://developers.asana.com',
    scopes: ['default'],
    serverUrl: 'https://mcp.asana.com/mcp',
    tools: ['asana_list_tasks', 'asana_create_task', 'asana_update_task', 'asana_list_projects']
  },

  // --- API KEY CONNECTORS (14) ---
  {
    slug: 'tavily',
    name: 'Tavily',
    category: 'search',
    description: 'Execute advanced web search queries optimized for LLM agent context.',
    authType: 'api_key',
    icon: 'ti-world-search',
    docsUrl: 'https://tavily.com',
    keyLabel: 'Tavily API Key',
    keyPlaceholder: 'tvly-...',
    keyDocsUrl: 'https://tavily.com/dashboard',
    serverUrl: 'https://mcp.tavily.com/mcp',
    tools: ['tavily_search', 'tavily_extract']
  },
  {
    slug: 'exa',
    name: 'Exa',
    category: 'search',
    description: 'Execute neural semantic searches matching documents and conceptual queries.',
    authType: 'api_key',
    icon: 'ti-search',
    docsUrl: 'https://exa.ai',
    keyLabel: 'Exa API Key',
    keyPlaceholder: 'exa-...',
    keyDocsUrl: 'https://exa.ai/dashboard',
    serverUrl: 'https://mcp.exa.ai/sse',
    tools: ['exa_search', 'exa_find_similar', 'exa_get_contents']
  },
  {
    slug: 'brave-search',
    name: 'Brave Search',
    category: 'search',
    description: 'Query Brave Web Search index for fresh information and links.',
    authType: 'api_key',
    icon: 'ti-shield-search',
    docsUrl: 'https://brave.com/search/api',
    keyLabel: 'Brave Search API Key',
    keyDocsUrl: 'https://api.search.brave.com',
    serverUrl: 'https://api.search.brave.com/mcp',
    tools: ['brave_web_search', 'brave_news_search']
  },
  {
    slug: 'perplexity',
    name: 'Perplexity',
    category: 'search',
    description: 'Query Perplexity LLM search engines for structured factual summaries.',
    authType: 'api_key',
    icon: 'ti-brain',
    docsUrl: 'https://docs.perplexity.ai',
    keyLabel: 'Perplexity API Key',
    keyDocsUrl: 'https://perplexity.ai/settings/api',
    serverUrl: 'https://mcp.perplexity.ai',
    tools: ['perplexity_search', 'perplexity_reason']
  },
  {
    slug: 'serper',
    name: 'Serper',
    category: 'search',
    description: 'Query Google Search APIs for news, places, local businesses, and image search metadata.',
    authType: 'api_key',
    icon: 'ti-brand-google',
    docsUrl: 'https://serper.dev',
    keyLabel: 'Serper API Key',
    keyDocsUrl: 'https://serper.dev/dashboard',
    serverUrl: 'https://mcp.serper.dev',
    tools: ['serper_search', 'serper_news', 'serper_images', 'serper_places']
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    category: 'finance',
    description: 'Check subscription statuses, pull customer payments, and track transactions.',
    authType: 'api_key',
    icon: 'ti-brand-stripe',
    docsUrl: 'https://stripe.com/docs/api',
    keyLabel: 'Stripe Secret Key',
    keyPlaceholder: 'sk_live_...',
    keyDocsUrl: 'https://dashboard.stripe.com/apikeys',
    serverUrl: 'https://mcp.stripe.com/sse',
    tools: ['stripe_list_customers', 'stripe_create_customer', 'stripe_list_payments', 'stripe_create_payment_link', 'stripe_list_subscriptions', 'stripe_create_invoice']
  },
  {
    slug: 'razorpay',
    name: 'Razorpay',
    category: 'finance',
    description: 'Generate orders, list customer profiles, and audit payment success rates.',
    authType: 'api_key',
    icon: 'ti-credit-card',
    docsUrl: 'https://razorpay.com/docs/api',
    keyLabel: 'Razorpay Key ID + Secret',
    keyDocsUrl: 'https://dashboard.razorpay.com/app/keys',
    serverUrl: 'https://mcp.razorpay.com/mcp',
    tools: ['razorpay_list_payments', 'razorpay_create_order', 'razorpay_list_customers']
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    category: 'developer',
    description: 'Manage backend databases, query table schemas, and execute functions.',
    authType: 'api_key',
    icon: 'ti-database',
    docsUrl: 'https://supabase.com/docs',
    keyLabel: 'Supabase Service Role Key',
    keyDocsUrl: 'https://supabase.com/dashboard/project/settings/api',
    serverUrl: 'https://mcp.supabase.com/sse',
    tools: ['supabase_query', 'supabase_insert', 'supabase_update', 'supabase_list_tables']
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    category: 'developer',
    description: 'Inspect deployment builds, deploy domains, and manage cloud hosting states.',
    authType: 'api_key',
    icon: 'ti-triangle',
    docsUrl: 'https://vercel.com/docs',
    keyLabel: 'Vercel API Token',
    keyDocsUrl: 'https://vercel.com/account/tokens',
    serverUrl: 'https://mcp.vercel.com/sse',
    tools: ['vercel_list_projects', 'vercel_list_deployments', 'vercel_get_deployment', 'vercel_create_deployment']
  },
  {
    slug: 'replicate',
    name: 'Replicate',
    category: 'ai',
    description: 'Run machine learning models in the cloud, query predictions, and compile outputs.',
    authType: 'api_key',
    icon: 'ti-cpu',
    docsUrl: 'https://replicate.com/docs',
    keyLabel: 'Replicate API Token',
    keyDocsUrl: 'https://replicate.com/account/api-tokens',
    serverUrl: 'https://mcp.replicate.com/mcp',
    tools: ['replicate_run_model', 'replicate_list_models', 'replicate_get_prediction']
  },
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'ai',
    description: 'Synthesize speech, list custom voice settings, and clone vocal accents.',
    authType: 'api_key',
    icon: 'ti-microphone',
    docsUrl: 'https://elevenlabs.io/docs',
    keyLabel: 'ElevenLabs API Key',
    keyDocsUrl: 'https://elevenlabs.io/profile',
    serverUrl: 'https://mcp.elevenlabs.io/mcp',
    tools: ['elevenlabs_text_to_speech', 'elevenlabs_list_voices', 'elevenlabs_clone_voice']
  },
  {
    slug: 'airtable',
    name: 'Airtable',
    category: 'data',
    description: 'Retrieve base records, read custom table layouts, and modify grids.',
    authType: 'api_key',
    icon: 'ti-table',
    docsUrl: 'https://airtable.com/api',
    keyLabel: 'Airtable Personal Access Token',
    keyDocsUrl: 'https://airtable.com/create/tokens',
    serverUrl: 'https://mcp.airtable.com/mcp',
    tools: ['airtable_list_bases', 'airtable_list_tables', 'airtable_query', 'airtable_create_record', 'airtable_update_record']
  },
  {
    slug: 'stability',
    name: 'Stability AI',
    category: 'ai',
    description: 'Generate high-fidelity artwork, edit styles, and scale image assets.',
    authType: 'api_key',
    icon: 'ti-photo-ai',
    docsUrl: 'https://platform.stability.ai',
    keyLabel: 'Stability AI API Key',
    keyDocsUrl: 'https://platform.stability.ai/account/keys',
    serverUrl: 'https://mcp.stability.ai/mcp',
    tools: ['stability_generate_image', 'stability_image_to_image', 'stability_upscale']
  },
  {
    slug: 'kaggle',
    name: 'Kaggle',
    category: 'data',
    description: 'Search datasets, download CSV structures, and check competition rankings.',
    authType: 'api_key',
    icon: 'ti-chart-dots',
    docsUrl: 'https://kaggle.com',
    keyLabel: 'Kaggle API Key (JSON)',
    keyDocsUrl: 'https://kaggle.com/settings',
    serverUrl: 'https://mcp.kaggle.com/mcp',
    tools: ['kaggle_search_datasets', 'kaggle_download_dataset', 'kaggle_list_competitions']
  },

  // --- NO-AUTH CONNECTORS (3) ---
  {
    slug: 'wikipedia',
    name: 'Wikipedia',
    category: 'search',
    description: 'Search articles, fetch summaries, and compile reference links.',
    authType: 'none',
    icon: 'ti-books',
    docsUrl: 'https://wikipedia.org',
    serverUrl: 'https://mcp.wikipedia.org/mcp',
    tools: ['wikipedia_search', 'wikipedia_get_article', 'wikipedia_get_summary']
  },
  {
    slug: 'openmeteo',
    name: 'Open-Meteo Weather',
    category: 'data',
    description: 'Query current weather conditions, read 7-day forecast profiles, and audit historical metrics.',
    authType: 'none',
    icon: 'ti-cloud-rain',
    docsUrl: 'https://open-meteo.com',
    serverUrl: 'https://mcp.open-meteo.com/mcp',
    tools: ['weather_current', 'weather_forecast', 'weather_historical']
  },
  {
    slug: 'hackernews',
    name: 'Hacker News',
    category: 'search',
    description: 'Query trending stories, read comment pages, and lookup top discussions.',
    authType: 'none',
    icon: 'ti-brand-redhat',
    docsUrl: 'https://news.ycombinator.com',
    serverUrl: 'https://mcp.hn.com/mcp',
    tools: ['hn_top_stories', 'hn_search', 'hn_get_comments']
  }
];
