export enum StreamEventType {
  // Orchestrator events
  ORCHESTRATOR_THINKING = 'ORCHESTRATOR_THINKING',
  ORCHESTRATOR_PLANNING = 'ORCHESTRATOR_PLANNING',
  ORCHESTRATOR_SPAWNING_AGENT = 'ORCHESTRATOR_SPAWNING_AGENT',
  ORCHESTRATOR_DISPATCHING = 'ORCHESTRATOR_DISPATCHING',
  ORCHESTRATOR_SYNTHESIZING = 'ORCHESTRATOR_SYNTHESIZING',
  ORCHESTRATOR_COMPLETE = 'ORCHESTRATOR_COMPLETE',

  // Agent events
  AGENT_STARTED = 'AGENT_STARTED',
  AGENT_THINKING = 'AGENT_THINKING',
  AGENT_OUTPUT_CHUNK = 'AGENT_OUTPUT_CHUNK',
  AGENT_COMPLETE = 'AGENT_COMPLETE',
  AGENT_FAILED = 'AGENT_FAILED',
  AGENT_REVISION_TRIGGERED = 'AGENT_REVISION_TRIGGERED',

  // Tool call events
  TOOL_CALLING = 'TOOL_CALLING',
  TOOL_RESULT = 'TOOL_RESULT',
  TOOL_FAILED = 'TOOL_FAILED',

  // Browser events
  BROWSER_OPENING = 'BROWSER_OPENING',
  BROWSER_NAVIGATING = 'BROWSER_NAVIGATING',
  BROWSER_SEARCHING = 'BROWSER_SEARCHING',
  BROWSER_EXTRACTING = 'BROWSER_EXTRACTING',
  BROWSER_ROW_FOUND = 'BROWSER_ROW_FOUND',
  BROWSER_COMPLETE = 'BROWSER_COMPLETE',
  BROWSER_CLOSED = 'BROWSER_CLOSED',

  // Judge events
  JUDGE_EVALUATING = 'JUDGE_EVALUATING',
  JUDGE_SCORING = 'JUDGE_SCORING',
  JUDGE_PASSED = 'JUDGE_PASSED',
  JUDGE_FAILED = 'JUDGE_FAILED',
  JUDGE_REVISION = 'JUDGE_REVISION',

  // Memory events
  MEMORY_SAVING = 'MEMORY_SAVING',
  MEMORY_RECALLED = 'MEMORY_RECALLED',
  MEMORY_EMBEDDED = 'MEMORY_EMBEDDED',

  // Inter-agent events
  AGENT_MESSAGE_SENT = 'AGENT_MESSAGE_SENT',
  AGENT_MESSAGE_RECEIVED = 'AGENT_MESSAGE_RECEIVED',
  AGENT_TASK_QUEUED = 'AGENT_TASK_QUEUED',

  // Price watch events
  PRICE_CHECKING = 'PRICE_CHECKING',
  PRICE_FOUND = 'PRICE_FOUND',
  PRICE_TARGET_HIT = 'PRICE_TARGET_HIT',
  PRICE_ALERT_SENT = 'PRICE_ALERT_SENT',

  // Ad intelligence events
  AD_INTEL_SCRAPING = 'AD_INTEL_SCRAPING',
  AD_INTEL_ANALYZING = 'AD_INTEL_ANALYZING',
  AD_INTEL_GENERATING = 'AD_INTEL_GENERATING',
  AD_FOUND = 'AD_FOUND',
  ADS_COMPLETE = 'ADS_COMPLETE',

  // CSO outreach events
  LEADS_SEARCHING = 'LEADS_SEARCHING',
  LEAD_FOUND = 'LEAD_FOUND',
  LEAD_RESEARCHING = 'LEAD_RESEARCHING',
  EMAIL_DRAFTING = 'EMAIL_DRAFTING',
  EMAIL_SENDING = 'EMAIL_SENDING',
  EMAIL_SENT = 'EMAIL_SENT',

  // Canvas events
  CANVAS_CREATING = 'CANVAS_CREATING',
  CANVAS_ROW_ADDED = 'CANVAS_ROW_ADDED',
  CANVAS_COMPLETE = 'CANVAS_COMPLETE',

  // Schedule events
  SCHEDULE_TRIGGERED = 'SCHEDULE_TRIGGERED',
  WEEKLY_RUN_STARTED = 'WEEKLY_RUN_STARTED',
  WEEKLY_RUN_COMPLETE = 'WEEKLY_RUN_COMPLETE',

  // System events
  STREAM_START = 'STREAM_START',
  STREAM_END = 'STREAM_END',
  STREAM_ERROR = 'STREAM_ERROR'
}

export interface StreamEvent {
  id: string;
  type: StreamEventType;
  timestamp: string;
  projectId: string;
  agentId?: string;
  agentName?: string;
  agentRole?: string;
  title: string;
  detail?: string;
  data?: Record<string, unknown>;
  progress?: number;
  status?: 'running' | 'done' | 'error';
}
